# YELP_CONSUMER_KEY: "-RwaodA3tArQPHUGUHm7Kg"
# YELP_CONSUMER_SECRET: "M-4iOKQhFJqNRhtYVMowzHEX3vo"
# YELP_TOKEN: "4_dt16aYqtAe-H4o0O1BaII0z3AwvO-U"
# YELP_TOKEN_SECRET: "UCCn32_ECM-94xQ194Y7nf6-ViA"


# CLIENT_ID = <YOUR_CLIENT_ID>
# CLIENT_SECRET = <YOUR_CLIENT_SECRET> (API Key)

YELP_CLIENT_ID: "hJpPg2orUBXtrXXPRMeVqg"
YELP_CLIENT_SECRET: "oOTi2oc4wI3H3-ujw4oy89MlP3FoSvQYAtbWWR4qHWQejC0n3GHzngXxLA_EnFjn0ofALfVF7MbEQaG3Zh_b132rKKAcZ9WTMSFv7AOBZ1-k4QkLKQBEj_ivm9b9WnYx"

